spring:
    profile: dev

    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
            
    datasource:
        url: jdbc:postgresql://localhost/springboot
        username: postgres
        password: postgres
