spring:
    profile: dev

    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
            

    datasource:
        platform: postgresql
        url: jdbc:postgresql://localhost/springboot
        username: postgres
        password: postgres
        driverClassName: org.postgresql.Driver
